### PR TITLE
Added is.sandbox() for macOS

### PR DESCRIPTION
**Pull request by jwheare**

### CODE REVIEW

**Comment by delvedor** [comment]
Hi, thanks for the PR!
Since this function is only for macOS, could you add something like this?
```javascript
IsApi.prototype.sandbox = function () {
  if (!this.macOS()) {
    throw new Error('is.sandbox() works only under macOS')
  }
  return 'APP_SANDBOX_CONTAINER_ID' in process.env
}
```
And maybe write some tests :)

**Comment by jwheare** [comment]
I don't think it should throw an error, returning false when it's not macOS would make more sense imo. For instance, I'm using this in my app at the moment like this:

```
var supported = (is.macOS() || is.windows()) && !is.sandbox();
```

Perhaps it could be renamed `is.macSandbox` if you prefer.

I'll add a test.

**Comment by jwheare** [comment]
I force pushed a test and fixed the macOS release tests (latest is now 10.11.6, this seems a bit brittle)

**Comment by delvedor** [comment]
Ok, sounds good.
About the test I've planned to update it, as soon as I have a bit 'of time :)

Thank you!

**Pull request merged**
